@echo off

set CURRENTFOLDER=%~d0%~p0
set POSTERAZORVERSION=1.4
set DISTRIBUTIONNAME=PosteRazor-%POSTERAZORVERSION%-Win32
set DISTRIBUTIONFOLDER=%CURRENTFOLDER%%DISTRIBUTIONNAME%\
set DISTRIBUTIONARCHIVENAME=%DISTRIBUTIONNAME%.zip
set DISTRIBUTIONARCHIVE=%CURRENTFOLDER%%DISTRIBUTIONARCHIVENAME%
set PACKEREXECUTABLE=upx.exe
set ZIPEXECUTABLE=7z.exe

rd /S /Q %DISTRIBUTIONFOLDER%
rd /Q %DISTRIBUTIONARCHIVE%

md %DISTRIBUTIONFOLDER%
xcopy /v %CURRENTFOLDER%Release\PosteRazorUI.exe %DISTRIBUTIONFOLDER%
ren %DISTRIBUTIONFOLDER%PosteRazorUI.exe PosteRazor.exe
%PACKEREXECUTABLE% --best %DISTRIBUTIONFOLDER%PosteRazor.exe

xcopy /v %CURRENTFOLDER%..\..\..\CHANGES %DISTRIBUTIONFOLDER%
xcopy /v %CURRENTFOLDER%..\..\..\LICENSE %DISTRIBUTIONFOLDER%
xcopy /v %CURRENTFOLDER%..\..\..\README %DISTRIBUTIONFOLDER%

%ZIPEXECUTABLE% a -r -tzip %DISTRIBUTIONARCHIVE% %DISTRIBUTIONFOLDER%*.*
