@echo off

set CURRENTFOLDER=%~d0%~p0
set POSTERAZORVERSION=1.4
set DISTRIBUTIONNAME=PosteRazor-%POSTERAZORVERSION%-Win32
set DISTRIBUTIONFOLDER=%CURRENTFOLDER%%DISTRIBUTIONNAME%\
set DISTRIBUTIONARCHIVENAME=%DISTRIBUTIONNAME%.zip
set DISTRIBUTIONARCHIVE=%CURRENTFOLDER%%DISTRIBUTIONARCHIVENAME%
set PACKEREXECUTABLE=upx.exe
set ZIPEXECUTABLE=7z.exe

rd /S /Q "%DISTRIBUTIONFOLDER%"
rd /Q "%DISTRIBUTIONARCHIVE%"

md "%DISTRIBUTIONFOLDER%"
xcopy /v "%CURRENTFOLDER%Release\PosteRazorUI.exe" "%DISTRIBUTIONFOLDER%"
ren "%DISTRIBUTIONFOLDER%PosteRazorUI.exe" PosteRazor.exe
"%PACKEREXECUTABLE%" --best --ultra-brute "%DISTRIBUTIONFOLDER%PosteRazor.exe"

for %%i in (CHANGES LICENSE README) do xcopy /v "%CURRENTFOLDER%..\..\..\%%i" "%DISTRIBUTIONFOLDER%"

del "%DISTRIBUTIONARCHIVE%"
"%ZIPEXECUTABLE%" a -r -tzip "%DISTRIBUTIONARCHIVE%" "%DISTRIBUTIONFOLDER%*"
